## Burley and Woodhead Attendance data

```{r}
library(tidyverse)
library(foreach)
library(iterators)
library(rjags)
```

```{r}
# load attendance data
attendance <- read_csv("data/brad_la_school_attendance_full.csv")

# add study arms to data
attendance$arm <- 0
arm1 = c(
  "Horton Grange Primary School", "Bradford Academy", 
  "Cavendish Primary School", "St Matthew's Catholic Primary School", 
  "Farnham Primary School", "St Joseph's Catholic Primary School (Bingley)", 
  "Green Lane Primary School", "Westbourne Primary School", 
  "Margaret McMillan Primary School", "Beckfoot Nessfield", 
  "Beckfoot Priestthorpe Primary School & Nursery"
)
attendance[attendance$school %in% arm1, "arm"] <- 1
arm2 = c(
  "Eastwood Community School", "Shirley Manor Primary School",  
  "Swain House Primary School", "Bowling Park Primary School", 
  "Burley and Woodhead CofE Primary School", "Crossflatts Primary School", 
  "Copthorne Primary School", "St Columba's Catholic Primary School", 
  "St Joseph's Catholic Primary School (Bradford)", 
  "St William's Catholic Primary School"
)
attendance[attendance$school %in% arm2, "arm"] <- 2
arm3 = c(
  "Riddlesden St Mary's CofE Primary School", "Newby Primary School", 
  "Thackley Primary School", "Addingham Primary School", 
  "The Academy At St. James", "St Paul's CofE Primary School", 
  "Clayton Village Primary School", "Sandal Primary School", 
  "Grove House Primary School", "Saltaire Primary School"
)
attendance[attendance$school %in% arm3, "arm"] <- 3
attendance <- attendance %>% mutate(hepa_arm = arm == 2)

# convert week_start to date format
attendance <- attendance %>% 
  mutate(week_start = as.Date(week_start, format="%m/%d/%y"))

# remove stray october date
attendance <- attendance %>% filter(week_start > "2021-09-01")

# rename St Joseph's schools to make easier to differentiate
attendance <- attendance %>% 
  mutate(school = replace(school, 
                          school == "St Joseph's Catholic Primary School (Bingley)",  
                          "St Joseph's Bingley")) %>%
  mutate(school = replace(school, 
                          school == "St Joseph's Catholic Primary School (Bradford)",  
                          "St Joseph's Bradford"))

# shorten down school names
shorten_name <- function(name) {
    words = unlist(strsplit(name, " "))
    if(length(words) >= 3) {
      paste(words[1:3], collapse=" ")
    } else {
      paste(words, collapse=" ")
    }
}
attendance <- attendance %>% 
  mutate(school = sapply(school, shorten_name))

# add extra aggregate data and reorder
attendance <- attendance %>%
  mutate(other_attendance = rowSums(across(c(L, B, D, J, P, V, W)))) %>%
  mutate(covid_absences = rowSums(across(c(I02, X06, X07, X02, X09, X08, X)))) %>%
  mutate(all_sessions = possible_sessions + covid_absences + I01 + Y + `#`) %>%
  mutate(diff = total_sessions - all_sessions) %>%
  relocate(other_attendance, .after=pm) %>%
  relocate(covid_absences, .after=U) %>%
  relocate(all_sessions, .after=total_sessions) %>%
  relocate(diff, .after=all_sessions)

str(attendance)
```

### 20 Sep

```{r}

# collect relevant LA data for problem weeks
ignore_cols <- c("school", "total_sessions", "diff", 
                 "all_sessions",  "possible_sessions", "sessions_attended", 
                 "other_attendance", "authorised",  "unauthorised", 
                 "covid_absences", "arm",  "hepa_arm")
comparison_data <- attendance %>% 
    filter(school == "Burley and Woodhead" & 
               week_start %in% as.Date(c("2021-10-18", "2021-09-20"))) %>% 
    select(-all_of(ignore_cols))

# calculate attendance figures for w/c 20/9 from Burley data and add 
burley_data_20_9 <- read_csv("data/burley&woodhead_attendance_20-09-21.csv")
burley_chars_20_9 <- unname(unlist(c(burley_data_20_9)))
comparison_data[3,] <- NA
for (col_name in names(comparison_data)) {
    if (col_name == "am") {
        char = "/"
    } else if (col_name == "week_start") {
        comparison_data[3, "week_start"] <- as.Date("2021-09-20")
        next
    } else if (col_name == "pm") {
        char = "\\"
    } else {
        char = col_name
    }
    comparison_data[3, col_name] <- sum(burley_chars_20_9 == char)
}
comparison_data[3, "total_pupils"] <- nrow(burley_data_20_9)
comparison_data[3, "#"] <- nrow(burley_data_20_9) * 4


# calculate attendance figures for w/c 21/10 from Burley data and add 
burley_data_10_21 <- read_csv("data/burley&woodhead_attendance_18-10-21.csv")
burley_chars_10_21 <- unname(unlist(c(burley_data_10_21)))
comparison_data[4,] <- NA
for (col_name in names(comparison_data)) {
    if (col_name == "am") {
        char = "/"
    } else if (col_name == "week_start") {
        comparison_data[4, "week_start"] <- as.Date("2021-10-18")
        next
    } else if (col_name == "pm") {
        char = "\\"
    } else {
        char = col_name
    }
    comparison_data[4, col_name] <- sum(burley_chars_10_21 == char)
}
comparison_data[4, "total_pupils"] <- nrow(burley_data_10_21)
comparison_data[4, "#"] <- nrow(burley_data_10_21) * 4

comparison_data["Source"] = c("LA", "LA", 
                              "Burley & Woodhead",  "Burley & Woodhead")
comparison_data <- comparison_data %>% 
    relocate(Source, .before=week_start) %>% 
    arrange(week_start)
```
```{r}
comparison_data %>% gather("observation", "value", -c(1,2)) %>% 
  write_csv("data/LA_burley_comparison.csv")
```

